### ISSUE TITLE
Unable to fetch seq info. Server down?

### ISSUE THREAD

**Issue by daanhazelaar** [Bioconductor/GenomeInfoDb#103]
Hi,

I get the following error message when fetching Seqinfo:

> GenomeInfoDb::Seqinfo(genome="hg38")
Error in download.file(url, destfile, quiet = TRUE) : 
  cannot open URL 'http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz'

Is the server down?

**Comment by LiNk-NY** [comment]
Hi Daan, @daanhazelaar 
Thanks for letting us know. 
We were aware of the error and it has affected many of our packages. 
It is not an issue for `GenomeInfoDb` but rather for the hosting site. 

In the meantime, you can use the backup server as posted here: 
https://github.com/Bioconductor/GenomeInfoDb/issues/102

Best,
Marcel
