### ISSUE TITLE
Installing DESeq2 Error: no package called ‘GenomeInfoDbData’

### ISSUE THREAD

**Issue by emailjack** [Bioconductor/GenomeInfoDb#11]
Just updated my previous R to 4.01 and now I cant load DESeq2.

When trying to load it again I get this:
> library(DESeq2)
Loading required package: GenomicRanges
Loading required package: GenomeInfoDb
Error: package or namespace load failed for ‘GenomeInfoDb’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘GenomeInfoDbData’
Error: package ‘GenomeInfoDb’ could not be loaded

So I tried to load that package:

> if (!requireNamespace("BiocManager", quietly = TRUE))
+     install.packages("BiocManager")
> 
> BiocManager::install("GenomeInfoDbData")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.1 (2020-06-06)
Installing package(s) 'GenomeInfoDbData'
installing the source package ‘GenomeInfoDbData’

trying URL 'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/GenomeInfoDbData_1.2.3.tar.gz'
Content type 'application/x-gzip' length 10413139 bytes (9.9 MB)
==================================================
downloaded 9.9 MB

dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34:  9542 Done                    echo 'tools:::.install_packages()'
      9543 Abort trap: 6           | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --no-echo --args ${args}

The downloaded source packages are in
	‘/private/var/folders/0t/8jm6lgqs0qj63rprpf9q_nfw0000gn/T/RtmpMNoZz3/downloaded_packages’
Old packages: 'RcppArmadillo', 'survival'
Update all/some/none? [a/s/n]: 
a

  There are binary versions available but the source versions are later:
                   binary      source needs_compilation
RcppArmadillo 0.9.880.1.0 0.9.900.1.0              TRUE
survival           3.1-12       3.2-3              TRUE

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) no
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/RcppArmadillo_0.9.880.1.0.tgz'
Content type 'application/x-gzip' length 1863064 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/survival_3.1-12.tgz'
Content type 'application/x-gzip' length 7849515 bytes (7.5 MB)
==================================================
downloaded 7.5 MB

The downloaded binary packages are in
	/var/folders/0t/8jm6lgqs0qj63rprpf9q_nfw0000gn/T//RtmpMNoZz3/downloaded_packages
Warning message:
In install.packages(...) :
  installation of package ‘GenomeInfoDbData’ had non-zero exit status

Any advice folks?

**Comment by mtmorgan** [comment]
Can you clarify how you updated your R to 4.0.1?

**Comment by emailjack** [comment]
uninstalled R. Downloaded the new one:

> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Sierra 10.12.6

**Comment by mtmorgan** [comment]
I'm trying to reproduce your problem, so being as precise as possible is important. I downloaded the R-4.0.1.pkg link from https://cran.r-project.org/bin/macosx/ and installed it as an administrator.

I then launched the R application (from the finder, not RStudio) and installed BiocManager
```
install.packages("BiocManager", repos = "https://cran.r-project.org")
```
and the current version of Bioconductor
```
BiocManager::install()
```
And finally installed GenomeInfoDbData
```
> BiocManager::install("GenomeInfoDbData")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.1 (2020-06-06)
Installing package(s) 'GenomeInfoDbData'
installing the source package 'GenomeInfoDbData'

trying URL 'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/GenomeInfoDbData_1.2.3.tar.gz'
Content type 'application/x-gzip' length 10413139 bytes (9.9 MB)
==================================================
downloaded 9.9 MB

* installing *source* package 'GenomeInfoDbData' ...
** using staged installation
** data
** inst
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (GenomeInfoDbData)

The downloaded source packages are in
	'/private/var/folders/yn/gmsh_22s2c55v816r6d51fx1tnyl61/T/RtmpyuWiYE/downloaded_packages'
Installation path not writeable, unable to update packages: survival
> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_4.0.1      tools_4.0.1        
```
So I've had success.

What do I need to do to reproduce your problem?

**Comment by coffeeCowLu** [comment]
> version

thankyou very much!!!  well done!

**Comment by coffeeCowLu** [comment]
> I'm trying to reproduce your problem, so being as precise as possible is important. I downloaded the R-4.0.1.pkg link from https://cran.r-project.org/bin/macosx/ and installed it as an administrator.
> 
> I then launched the R application (from the finder, not RStudio) and installed BiocManager
> 
> ```
> install.packages("BiocManager", repos = "https://cran.r-project.org")
> ```
> 
> and the current version of Bioconductor
> 
> ```
> BiocManager::install()
> ```
> 
> And finally installed GenomeInfoDbData
> 
> ```
> > BiocManager::install("GenomeInfoDbData")
> Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.1 (2020-06-06)
> Installing package(s) 'GenomeInfoDbData'
> installing the source package 'GenomeInfoDbData'
> 
> trying URL 'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/GenomeInfoDbData_1.2.3.tar.gz'
> Content type 'application/x-gzip' length 10413139 bytes (9.9 MB)
> ==================================================
> downloaded 9.9 MB
> 
> * installing *source* package 'GenomeInfoDbData' ...
> ** using staged installation
> ** data
> ** inst
> ** help
> *** installing help indices
> ** building package indices
> ** testing if installed package can be loaded from temporary location
> ** testing if installed package can be loaded from final location
> ** testing if installed package keeps a record of temporary installation path
> * DONE (GenomeInfoDbData)
> 
> The downloaded source packages are in
> 	'/private/var/folders/yn/gmsh_22s2c55v816r6d51fx1tnyl61/T/RtmpyuWiYE/downloaded_packages'
> Installation path not writeable, unable to update packages: survival
> > sessionInfo()
> R version 4.0.1 (2020-06-06)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS High Sierra 10.13.6
> 
> Matrix products: default
> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] BiocManager_1.30.10 compiler_4.0.1      tools_4.0.1        
> ```
> 
> So I've had success.
> 
> What do I need to do to reproduce your problem?

thankyou very much !!! well done~

**Comment by hpages** [comment]
> thankyou very much !!! well done~

I guess that means we can finally close this issue.

Best,
H.
