### ISSUE TITLE
error in seqlevelsStyle()

### ISSUE THREAD

**Issue by yloskove** [Bioconductor/GenomeInfoDb#110]
Hi, 

When I try to run  `seqlevelsStyle(annotation) <- "UCSC"` I receive the following error: 

`Error in download.file(url, destfile, quiet = TRUE): cannot open URL 'https://hgdownload.soe.ucsc.edu/goldenPath/mm10/database/chromInfo.txt.gz'`

Can you please help with this and how to connect to the UCSC annotation database

**Comment by LiNk-NY** [comment]
Hi @yloskove 

When I browse to the URL, I get a download prompt. The link seems to be working OK.
Make sure that your firewall / proxy is not blocking that resource. 

Please also provide a reproducible example and include the version of 
`GenomeInfoDb` that you are using. 

Best,
Marcel

**Comment by yloskove** [comment]
Hi @LiNk-NY 

I'm not sure why, but I ran the code again and it seems to be working now!

**Comment by LiNk-NY** [comment]
Great!
