### ISSUE TITLE
Seqinfo constructor should auto-fill seqlevels= when seqlengths= is named

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/GenomeInfoDb#18]
Currently, construction from a named character vector looks like:

```r
lens <- c(chrA=1, chrB=2)
Seqinfo(seqlevels=names(lens), seqlengths=lens)
```

However, if `seqlengths=` is named, I would have expected the following to suffice:
```r
Seqinfo(seqlengths=lens)
```

and have `seqlevels=names(seqlengths)` by default. This would avoid the need to specify two arguments and allow convenient manual specification by passing in a single named vector directly to `seqlengths=`:

```r
Seqinfo(seqlengths=c(chrA=1, chrB=2, chrC=3))
```

**Comment by hpages** [comment]
Done in GenomeInfoDb 1.27.4 (see commit c3286ff0262a0d6cdf99c468522a0f2e29b19413).
