### ISSUE TITLE
Comparing Seqinfo objects

### ISSUE THREAD

**Issue by lawremi** [Bioconductor/GenomeInfoDb#2]
It might be nice to support some comparison operations between two Seqinfo objects, particularly `match()`. Then, if Seqinfo were a Vector (shouldn't it be?), we could do, for example:
```
all(seqinfo(which) %in% seqinfo(x))
```
to check whether the universe of `which` is a subset of that of `x`.

I think `match()` should consider the tuple of sequence name and genome version, where the `NA` version is wildcard. I noticed that e.g. `intersect,Seqinfo,Seqinfo()` just considers seqnames.

**Comment by hpages** [comment]
Checking that 2 objects have ranges on compatible underlying sequences should be done with `merge(seqinfo(x), seqinfo(y)) ` or some variant of it. There are numerous examples in GenomicRanges/setops-methods.R and GenomicRanges/GNCList-class.R. Isn't your use case covered by this?

`match()` should be consistent with `==` and `==` should not handle wildcards or we will end up with things like `x == y` and `y == z` and `x != z`. In other words `match()` is about exact matching, not fuzzy matching. I'm all for trying to make things more convenient but not at any cost!

`intersect,Seqinfo,Seqinfo()` just considers seqnames but it tries to merge the 2 objects first so will fail with an informative error message if a common seqname is associated with different genomes in the 2 objects.

**Comment by lawremi** [comment]
I was thinking about using `merge()` but I don't really want to merge anything. I just want to check that one set of ranges come from the same context as another set. Why not have an explicit check? In the common query case, we want to check whether the query comes from a subset of the region covered by the database, and it would be nice to make that explicit. You're right though that it doesn't make sense to treat Seqinfo as a Vector.

**Comment by hpages** [comment]
`merge()` performs both: the check and the merging. If you are not interested in the merging, just ignore the returned value. That's what the `match()` method for GenomicRanges objects does:
```
setMethod("match", c("GenomicRanges", "GenomicRanges"),
    function(x, table, nomatch=NA_integer_, incomparables=NULL,
                       method=c("auto", "quick", "hash"),
                       ignore.strand=FALSE)
    {
        ...
        ## Calling merge() is the way to check that 'x' and 'table' are based
        ## on the same reference genome.
        merge(seqinfo(x), seqinfo(table))
        ....
    }
)
```
We could add a `check_compatible_seqinfo()` in GenomeInfoDb. It would just do:
```
check_compatible_seqinfo <- function(x, y) merge(seqinfo(x), seqinfo(y))
```
Would that help?

**Comment by lawremi** [comment]
That would be OK. I would have expected the checking part to be factored out from `merge()`. Anyway, could this please be exported? I guess it would need a camel case name.

**Comment by hpages** [comment]
[Done](https://github.com/Bioconductor/GenomeInfoDb/commit/f1261c6cac41b7ddeaa1218b41bb9de8be092dbf).

The hard work in `merge()` is the checking, not the merging. The merging just happens to be very easy to do along the checking, as a side task, with almost no extra cost. An analogy would be a `findSmallestFactor()` function that finds the smallest non-one factor of a positive integer. Once you have it, it's easy to implement the `isPrimeNumber()` function as a trivial wrapper to `findSmallestFactor()`. There is not much to be gained by factoring out the part that tells you whether the number is prime or or not as this part would still have a hard problem to solve.

Just an analogy. Not that the difficulty of checking seqinfo compatibility is anywhere close to determining whether a number is prime or not ;-) Anyway feel free to submit a PR if you feel that your use case would benefit from such factoring out.

**Comment by hpages** [comment]
Hope that worked for you. Closing this now.
