### ISSUE TITLE
Error in .make_Seqinfo_from_genome(genome) 

### ISSUE THREAD

**Issue by liqian-ma** [Bioconductor/GenomeInfoDb#22]
I was trying to import `alevin` counts to R using `tximeta`, which depends on the package `GenomeinfoDb`. However, since I used the GRCm39 (Release M26) from Gencode for alignment and annotation. I encountered the following error from `GenomeinfoDb`:

```
Error in .make_Seqinfo_from_genome(genome) : 
  "GRCm39" is not a registered NCBI assembly or UCSC genome (use
  registered_NCBI_assemblies() or registered_UCSC_genomes() to list the NCBI or UCSC
  assemblies/genomes currently registered in the GenomeInfoDb package)
```

Is there a fix for this error, since GRCm39 was released in 2020?

Thank you very much for your help in advance!

**Comment by hpages** [comment]
Hi @liqian-ma ,

I registered GRCm39 in GenomeInfoDb 1.26.5 (release) and GenomeInfoDb 1.27.9 (devel). Both versions should propagate and become available via `BiocManager::install()` in the next 36 hours or so.

Best,
H.

**Comment by liqian-ma** [comment]
Thank you so much for the prompt help!
