### ISSUE TITLE
installation of GenomeInfoDbData failed

### ISSUE THREAD

**Issue by qlan20** [Bioconductor/GenomeInfoDb#29]
Hello,

The GenomeInfoDbData somehow failed to be installed (a dependency of GenomeInfoDb). I was wondering whether anyone has a clue on this issue?
I restarted with a newly-installed R but got the same error. Thanks in advance!

rtools40 was installed in C:\rtools40\usr\bin and was in Sys.getenv('PATH')

> Sys.which('make')
 make 
"C:\\rtools40\\usr\\bin\\make.exe"

> BiocManager::install("GenomeInfoDbData")

'getOption("repos")' replaces Bioconductor
standard repositories, see '?repositories' for
details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.13 (BiocManager 1.30.16),
  R 4.1.1 (2021-08-10)
Installing package(s) 'BiocVersion',
  'GenomeInfoDbData'
trying URL 'https://bioconductor.org/packages/3.13/bioc/bin/windows/contrib/4.1/BiocVersion_3.13.1.zip'
Content type 'application/zip' length 9399 bytes
downloaded 9399 bytes

package ‘BiocVersion’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\name\AppData\Local\Temp\RtmpyqbAD8\downloaded_packages
installing the source package ‘GenomeInfoDbData’

trying URL 'https://bioconductor.org/packages/3.13/data/annotation/src/contrib/GenomeInfoDbData_1.2.6.tar.gz'
Content type 'application/x-gzip' length 10973004 bytes (10.5 MB)
downloaded 10.5 MB

The downloaded source packages are in
	‘C:\Users\name\AppData\Local\Temp\RtmpyqbAD8\downloaded_packages’
Old packages: 'lattice', 'nlme', 'survival'
Update all/some/none? [a/s/n]: 
n
Warning message:
In .inet_warning(msg) :
  installation of package ‘GenomeInfoDbData’ had non-zero exit status

> sessionInfo()

R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 65001

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.16 compiler_4.1.1     
[3] tools_4.1.1

**Comment by hpages** [comment]
Hi @qlan20,

If you're still having problem installing the **GenomeInfoDbData** package, please ask on the [Bioconductor support site](https://support.bioconductor.org/). It will be appreciated if you can make proper use of markdown when you post there. This will make your post easier to read and understand.

Thanks,
H.
