### ISSUE TITLE
GRCh38.p14 covers T2T-CHM13 information, correct? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [Bioconductor/GenomeInfoDb#37]
I am wondering GRCh38.p14 covers T2T-CHM13 information, correct? 

Thanks.

Shicheng

**Comment by hpages** [comment]
I don't know. But I'm confused, we don't control what GRCh38.p14 covers do we?

H.

**Comment by hpages** [comment]
I actually don't think that GRCh38.p14 "covers" T2T-CHM13 information, whatever that means. Those are 2 completely different projects, the former from the Genome Reference Consortium and the latter from the T2T Consortium. But best way to find out is to read the release notes for GRCh38.p14 (if there is such a thing), or contact the GRC directly. Also have you tried to search for "GRCh38.p14 vs T2T-CHM13" on Google?

Anyways, in the meantime we've wrapped the T2T-CHM13 assembly in a BSgenome data package: https://bioconductor.org/packages/BSgenome.Hsapiens.NCBI.T2T.CHM13v2.0

Best,
H.
