### ISSUE TITLE
Error: package or namespace load failed for ‘GenomeInfoDb’; there is no package called ‘GenomeInfoDbData’

### ISSUE THREAD

**Issue by chancharikmitra** [Bioconductor/GenomeInfoDb#42]
I am having this issue of my jupyter notebook not being able to find the GenomeInfoDbData package even though it is already installed in my conda environment. Note: I am trying to use this package as part of the SpatialExperiment library.

Conda Version: 4.14.0
Running locally on macOS 11.6
Environment Dependencies:
[requirements.txt](https://github.com/Bioconductor/GenomeInfoDb/files/9668002/requirements.txt)

Error Readout when running library(SpatialExperiment) in a jupyter notebook:

`Loading required package: SingleCellExperiment

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats

Attaching package: ‘MatrixGenerics’

The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars

Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics

Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges

Loading required package: GenomeInfoDb

Error: package or namespace load failed for ‘GenomeInfoDb’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘GenomeInfoDbData’

Error: package ‘GenomeInfoDb’ could not be loaded
Traceback:

1. library(SpatialExperiment)
2. .getRequiredPackages2(pkgInfo, quietly = quietly)
3. library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc, 
 .     quietly = quietly)
4. .getRequiredPackages2(pkgInfo, quietly = quietly)
5. library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc, 
 .     quietly = quietly)
6. .getRequiredPackages2(pkgInfo, quietly = quietly)
7. library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc, 
 .     quietly = quietly)
8. .getRequiredPackages2(pkgInfo, quietly = quietly)
9. stop(gettextf("package %s could not be loaded", sQuote(pkg)), 
 .     call. = FALSE, domain = NA)`

**Comment by hpages** [comment]
This looks like a conda environment/configuration problem. How do you know that **GenomeInfoDbData** is already installed in your conda environment. Can you `library(GenomeInfoDbData)`?

Note that Bioconductor has no control on how Bioconductor packages get re-distributed and installed via conda. The only installation method that we support is `BiocManager::install()`.

**Comment by chancharikmitra** [comment]
I see. The requirements.txt file includes every package that is installed on the environment. This comes from running `conda list`. GenomeInfoDBData specifically version 1.2.4 is included. 
So you're saying this is likely a conda issue then?

**Comment by hpages** [comment]
> The requirements.txt file includes every package that is installed on the environment. This comes from running conda list.

Sounds good but that's not direct evidence that you _actually_ have **GenomeInfoDbData** installed in your conda environment, and that the package can be loaded. Only way to know _for sure_ is to try `library(GenomeInfoDbData)`. Did you try that?

**Comment by chancharikmitra** [comment]
@hpages Ah, I see what you are saying. `library(GenomeInfoDbData)` gives me 

_Error in library(GenomeInfoDbData): there is no package called ‘GenomeInfoDbData’
Traceback:

1. library(GenomeInfoDbData)_

Oddly enough, conda says this package is already installed when I try to reinstall it.

**Comment by hpages** [comment]
`library(GenomeInfoDbData)` is telling the truth: you don't have **GenomeInfoDbData** installed. Or maybe it is installed, but in the "wrong" place, whatever that means in the context of a conda installation.

Anyways, this is a conda installation issue. Can't help you with that, sorry.
