### ISSUE TITLE
Register NCBI assembly bStrHab1.2.pri

### ISSUE THREAD

**Issue by kakopo** [Bioconductor/GenomeInfoDb#80]
`bStrHab1.2.pri`  is an assembly name for the kakapo bird (Strigops habroptila) on the NCBI website: https://www.ncbi.nlm.nih.gov/assembly/GCF_004027225.2
I intend to register it within GenomeInfoDb.

**Comment by hpages** [comment]
Done in **GenomeInfoDb** 1.37.4 (see commit 564965fcb527668f4478a92409e8c743970749ab).
