### ISSUE TITLE
Installation non-zero exit status issue 

### ISSUE THREAD

**Issue by jackbrougher** [Bioconductor/GenomeInfoDb#85]
Hello,

I'm running into the same issue where trying to install GenomeInfoDb and GenomeInfoDbData both return the same non-zero exit status error.

Session Info:

> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4
Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] IRanges_2.32.0        S4Vectors_0.36.1      BiocGenerics_0.44.0   MatrixGenerics_1.10.0 matrixStats_0.63.0   
loaded via a namespace (and not attached):
[1] BiocManager_1.30.19 compiler_4.2.2      tools_4.2.2   

> BiocManager::install("GenomeInfoDb")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.microsoft.com

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31)
Installing package(s) 'GenomeInfoDb'
also installing the dependency ‘GenomeInfoDbData’

  There is a binary version available but the source version is later:
             binary source needs_compilation
GenomeInfoDb 1.34.7 1.34.8             FALSE

installing the source packages ‘GenomeInfoDbData’, ‘GenomeInfoDb’

trying URL 'https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz'
Content type 'application/x-gzip' length 11725198 bytes (11.2 MB)
==================================================
downloaded 11.2 MB

trying URL 'https://bioconductor.org/packages/3.16/bioc/src/contrib/GenomeInfoDb_1.34.8.tar.gz'
Content type 'application/x-gzip' length 3473340 bytes (3.3 MB)
==================================================
downloaded 3.3 MB

The downloaded source packages are in
	‘/private/var/folders/1m/13wf4t_57ys6_wfbt1qn9w8m0000gn/T/RtmpJ9EXZ6/downloaded_packages’
Warning messages:
1: In install.packages(...) :
  installation of package ‘GenomeInfoDbData’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘GenomeInfoDb’ had non-zero exit status

**Comment by hpages** [comment]
Hi @jackbrougher,

Are you still experiencing this problem? Note that the arm64 binary for **GenomeInfoDb** 1.34.8 is now available (`GenomeInfoDb_1.34.8.tgz`) so there's no need to install the source package. This generally makes installation much easier/faster. 

Also, and FWIW, it's not clear to me that you are showing the full output produced by `BiocManager::install("GenomeInfoDb")` in your post above. AFAICT the output shows only the download part but not the installation part, which is the most important part when installing packages from source. Without seeing the full output, it's impossible for us to know what went wrong.

Best,
H.

**Comment by hpages** [comment]
No new good news I guess
