### ISSUE TITLE
Packaging issue with conda/bioconda

### ISSUE THREAD

**Issue by gdevenyi** [Bioconductor/GenomeInfoDb#93]
The bioconda package of this is breaking things, discussion here:
https://github.com/bioconda/bioconda-recipes/issues/41870

**Comment by hpages** [comment]
I believe this has been resolved by now. See https://github.com/Bioconductor/GenomeInfoDbData/issues/6.

Best

**Comment by hpages** [comment]
Hope it's ok to close. @gdevenyi Feel free to re-open if you're still having issue with this.

**Comment by gdevenyi** [comment]
It wasn't the last time I tried (see https://github.com/bioconda/bioconda-recipes/issues/41870) updated posts.

I just fixed it myself in the end by creating a new environment from scratch which skipped whatever broken update step or such was happening.

**Comment by hpages** [comment]
Sounds good. In any case it didn't seem like an issue with **GenomeInfoDb** itself. More like an issue with conda/bioconda's packaging of the **GenomeInfoDbData** package.

**Comment by gdevenyi** [comment]
> conda/bioconda's packaging of the GenomeInfoDbData package.

Agree, just wasn't sure if the team here was involved in that.

**Comment by hpages** [comment]
No we're not. The only installation method endorsed and supported by Bioconductor is via `BiocManager::install()`: https://bioconductor.org/install/ People using anything else are on their own.
