### ISSUE TITLE
GenomeInfoDb::Seqinfo() may attach packages to the users' session

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/GenomeInfoDb#95]
Usually `Pkg::foo()` will load but not attach Pkg. But `GenomeInfoDb::Seqinfo()` will often attach IRanges, GenomeInfoDb, and friends, because of lines like

https://github.com/Bioconductor/GenomeInfoDb/blob/c0d17892e5d8271125ff10c22f0754ef1b2dfe1c/inst/registered/UCSC_genomes/apiMel1.R#L6-L7

For instance,

```
> GenomeInfoDb::Seqinfo(genome = "hg38")
Loading required package: BiocGenerics

Attaching package: 'BiocGenerics'
...
```
This is not desirable, because it alters the users `search()` path.

**Comment by hpages** [comment]
Thanks Martin. This is fixed in **GenomeInfoDb** 1.37.6 (devel) and 1.36.4 (release).
