### ISSUE TITLE
GenomeInfoDb - Registering the Sea Lamprey Genome 

### ISSUE THREAD

**Issue by hannahvanm** [Bioconductor/GenomeInfoDb#96]
Hi there, we're working on a multiomics dataset in the sea lamprey. We're processing our data using the Seurat WNN pipeline for 10X scRNA and sqATAC-seq and have run into an issue because the Sea lamprey genome is not one of the registered NCBI assemblies listed in GenomeInfoDb. We tried to make a reference genome to use from a GTF, which wasn't working, so it seems that using genomes currently registered in the GenomeInfoDb package would be easiest. 

Could we request that Genome assembly kPetMar1.pri ([NCBI RefSeq assembly GCF_010993605.1](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_010993605.1/)) be added the the registered assemblies list?

Here's the code we ran, followed by the error and session info. Thank you for your help! <3

```{r Make reference from GTF}

gtf <- rtracklayer::import('/Volumes/Hannah/T20 T24 multiome Stacy GTF allfilled/new.edited_SL_allfilled.gtf')
gene.coords <- gtf[gtf$type == 'gene']
seqlevelsStyle(gene.coords) <- 'UCSC'
gene.coords <- keepStandardChromosomes(gene.coords, pruning.mode = 'coarse')

lampgenome <- Rsamtools::FaFile("/Volumes/Hannah/Lamprey Genome Files/GCF_010993605.1_kPetMar1.pri_genomic.fna")
```

```{r}
grange.counts <- StringToGRanges(rownames(T24atac_counts), sep = c(":", "-"))
grange.use <- seqnames(grange.counts) %in% standardChromosomes(grange.counts)
T24atac_counts <- T24atac_counts[as.vector(grange.use), ]

myGranges<-as(gene.coords, "GRanges")

frag.file <- "/Volumes/Hannah/T20 T24 multiome Stacy GTF allfilled/T24_Stacy_allfilled/outs/atac_fragments.tsv.gz"

chrom_assay <- CreateChromatinAssay(
   counts = T24atac_counts,
   sep = c(":", "-"),
   genome = 'GCF_010993605.1',
   fragments = frag.file,
   min.cells = 10,
   annotation = myGranges
 )
T24[["ATAC"]] <- chrom_assay
```

Error in .make_Seqinfo_from_genome(genome) : 
  "GCF_010993605.1" is not a registered NCBI assembly or UCSC genome (use
  registered_NCBI_assemblies() or registered_UCSC_genomes() to list the NCBI or UCSC
  assemblies/genomes currently registered in the GenomeInfoDb package)

[multiome_session_info.txt](https://github.com/Bioconductor/GenomeInfoDb/files/13290678/multiome_session_info.txt)

**Comment by hpages** [comment]
OK, but only if you don't use **Seurat**...

... just kidding! :wink: 

Added to **GenomeInfoDb** 1.38.1 (BioC 3.18) and 1.39.1 (BioC 3.19, current devel).

Both versions should become available in the next 36-40 hrs via `BiocManager::install()`. If you can't wait then you can get the fix now by doing `remotes::install_github("Bioconductor/GenomeInfoDb@RELEASE_3_18")` if you're using BioC 3.18, or `remotes::install_github("Bioconductor/GenomeInfoDb")` if you're using BioC 3.19. However note that we usually _strongly_ advice against installing directly from GitHub so please consider this a one-time exception to the rule.

Best,
H.

**Comment by hannahvanm** [comment]
Thank you so much Hervé! We appreciate it!

Best,
Hannah

**Comment by hpages** [comment]
You're welcome.
